//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHeroService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperHeroService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	A-Bomb
        ///2	Abe Sapien
        ///3	Abin Sur
        ///4	Abomination
        ///5	Abraxas
        ///6	Absorbing Man
        ///7	Adam Monroe
        ///8	Adam Strange
        ///9	Agent 13
        ///10	Agent Bob
        ///11	Agent Zero
        ///12	Air-Walker
        ///13	Ajax
        ///14	Alan Scott
        ///15	Alex Mercer
        ///16	Alex Woolsly
        ///17	Alfred Pennyworth
        ///18	Alien
        ///19	Allan Quatermain
        ///20	Amazo
        ///21	Ammo
        ///22	Ando Masahashi
        ///23	Angel
        ///24	Angel
        ///25	Angel Dust
        ///26	Angel Salvadore
        ///27	Angela
        ///28	Animal Man
        ///29	Annihilus
        ///30	Ant-Man
        ///31	Ant-Man II
        ///32	Anti-Monitor
        ///33	Anti-Spawn
        ///34	Anti-Venom
        ///35	Apocalypse
        ///36	Aquababy
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string heroes {
            get {
                return ResourceManager.GetString("heroes", resourceCulture);
            }
        }
    }
}
