version: '3'

services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin@123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dbHero
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "pwd@123"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./scripts/create_database.sql:/docker-entrypoint-initdb.d/10-create_database.sql
      - ./scripts/create_table_hero.sql:/docker-entrypoint-initdb.d/20-create_table_complete_hero.sql
      - ./scripts/insert_hero_table.sql:/docker-entrypoint-initdb.d/30-insert_complete_hero_table.sql
    networks:
      - postgres-network
   
networks: 
  postgres-network:
    driver: bridge
    
    
##https://renatogroffe.medium.com/postgresql-pgadmin-4-docker-compose-montando-rapidamente-um-ambiente-para-uso-55a2ab230b89    